export interface Canvas {
  /** Unique identifier for the canvas */
  id?: number;

  /** Canvas display name or title */
  name: string;

  /** Image or preview URL (generated by backend or frontend) */
  image?: string;

  /** ID of the user/artist who created it */
  creatorId?: number;

  /** Optional creator/artist display name */
  creatorName?: string;

  /** Optional number of participants currently active */
  participants?: number;

  /** Canvas status (Active, Draft, or Closed) */
  status?: 'Active' | 'Draft' | 'Closed';

  /** Optional metadata (description, tags, etc.) */
  meta?: string;

  /** Whether the canvas is currently live (e.g. in session) */
  live?: boolean;

  /** Optional custom action label for UI (e.g. "Join", "Open") */
  actionText?: string;

  /** Date/time of creation */
  createdAt?: string;

  /** Date/time of last modification */
  updatedAt?: string;
}
